### ISSUE TITLE
Font face is different from current logo

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/pytest-design#1]
Hi 👋 

I noticed that [pytest_logo.svg](https://github.com/pytest-dev/pytest-design/blob/master/pytest_logo.svg) uses a different font than [pytest1.png](http://pytest.org/latest/_static/pytest1.png) that we use on the website.

Best
Raphael

**Comment by hackebrot** [comment]
[pytest_logo_curves.svg](https://github.com/pytest-dev/pytest-design/blob/master/pytest_logo_curves.svg) is fine! 😁

**Comment by kvas-it** [comment]
Hi Raphael,

I was just looking at both logos and I can't really find a difference
between the .png and the .svg. Since the curvy logo looks good for you, I'd
guess that perhaps you don't have the font installed on your system and
that why the texty logo looks different. The font is "Droid Sans" (I used
What the Font https://www.myfonts.com/WhatTheFont/ on the .png to recognise
it and it looks very similar to me).

The README of the repo documents the discrepancy to some extent, perhaps
it's not clear enough and perhaps we could improve that. If you can think
of a better way to alert potential users that the font is not embedded in
the texty svg, I'd be happy to update the README.

Cheers,
Vasily

**Comment by hackebrot** [comment]
Fair enough, _curvy_ does not use text but paths, which explains why it looks like the original to me w/o having the font installed. Perhaps adding a brief note along the lines of "You need to install **DroidSans** to your system to correctly display pytest_logo.svg".

**Comment by kvas-it** [comment]
Yeah, makes sense. I'll do that.

**Comment by hackebrot** [comment]
Thank you! 🙇
